#!/bin/sh
case $BLOCK_BUTTON in
	1)  gnome-calendar;;
	3)  dunstctl history-pop;;
	6) code "$0" ;;
esac

weekday=$(date '+%w')

case $weekday in
	1)  weekday="周一";;
	2)  weekday="周二";;
	3)  weekday="周三";;
	4)  weekday="周四";;
	5)  weekday="周五";;
	6)  weekday="周六";;
	0)  weekday="周日";;
	*)	weekday="错误${weekday}";;
esac
# 
echo "^B6^^C0^ $(date '+%T %m/%d') ${weekday}"