#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send " Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;		
	6) code "$0" ;;
esac


# echo "$(free --mebi | awk 'NR==2 {echo ("^B5^^C0^MEM %2.2fGiB\n", ($3 / 1024))}')"
echo "^B2^^C0^ $(free --mebi | awk 'NR==2 {printf ("%2.2fG\n", ($3 / 1024))}')"