#!/bin/sh

case $BLOCK_BUTTON in
	1)  nm-connection-editor ;;
	6) code "$0" ;;
esac

[ $(cat /sys/class/net/w*/operstate 2>/dev/null) = up ] && wifiIcon="直"

if [ $(cat /sys/class/net/e*/operstate 2>/dev/null) = up ]; then
	ethIcon=""
else
	if [ ! $wifiIcon ]; then
		echo "睊"
		exit 0
	fi
fi

[ "$(ip tuntap show)" ] && vpnIcon="嬨" || vpnIcon=""

echo "$wifiIcon$ethIcon$vpnIcon"